// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for PublicationStatus.
const (
	PublicationStatusAborted   PublicationStatus = "aborted"
	PublicationStatusCommitted PublicationStatus = "committed"
	PublicationStatusOpen      PublicationStatus = "open"
)

// Valid indicates whether the value is a known member of the PublicationStatus enum.
func (e PublicationStatus) Valid() bool {
	switch e {
	case PublicationStatusAborted:
		return true
	case PublicationStatusCommitted:
		return true
	case PublicationStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for UploadStatus.
const (
	Complete UploadStatus = "complete"
	Pending  UploadStatus = "pending"
)

// Valid indicates whether the value is a known member of the UploadStatus enum.
func (e UploadStatus) Valid() bool {
	switch e {
	case Complete:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for AbortPublication200JSONResponseBodyStatus.
const (
	AbortPublication200JSONResponseBodyStatusAborted   AbortPublication200JSONResponseBodyStatus = "aborted"
	AbortPublication200JSONResponseBodyStatusCommitted AbortPublication200JSONResponseBodyStatus = "committed"
	AbortPublication200JSONResponseBodyStatusOpen      AbortPublication200JSONResponseBodyStatus = "open"
)

// Valid indicates whether the value is a known member of the AbortPublication200JSONResponseBodyStatus enum.
func (e AbortPublication200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case AbortPublication200JSONResponseBodyStatusAborted:
		return true
	case AbortPublication200JSONResponseBodyStatusCommitted:
		return true
	case AbortPublication200JSONResponseBodyStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for GetPublication200JSONResponseBodyStatus.
const (
	GetPublication200JSONResponseBodyStatusAborted   GetPublication200JSONResponseBodyStatus = "aborted"
	GetPublication200JSONResponseBodyStatusCommitted GetPublication200JSONResponseBodyStatus = "committed"
	GetPublication200JSONResponseBodyStatusOpen      GetPublication200JSONResponseBodyStatus = "open"
)

// Valid indicates whether the value is a known member of the GetPublication200JSONResponseBodyStatus enum.
func (e GetPublication200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case GetPublication200JSONResponseBodyStatusAborted:
		return true
	case GetPublication200JSONResponseBodyStatusCommitted:
		return true
	case GetPublication200JSONResponseBodyStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for CommitPublication200JSONResponseBodyStatus.
const (
	CommitPublication200JSONResponseBodyStatusAborted   CommitPublication200JSONResponseBodyStatus = "aborted"
	CommitPublication200JSONResponseBodyStatusCommitted CommitPublication200JSONResponseBodyStatus = "committed"
	CommitPublication200JSONResponseBodyStatusOpen      CommitPublication200JSONResponseBodyStatus = "open"
)

// Valid indicates whether the value is a known member of the CommitPublication200JSONResponseBodyStatus enum.
func (e CommitPublication200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case CommitPublication200JSONResponseBodyStatusAborted:
		return true
	case CommitPublication200JSONResponseBodyStatusCommitted:
		return true
	case CommitPublication200JSONResponseBodyStatusOpen:
		return true
	default:
		return false
	}
}

// CreatePublication defines model for CreatePublication.
type CreatePublication struct {
	Account    string  `json:"account"`
	Label      *string `json:"label,omitempty"`
	Repository string  `json:"repository"`
}

// CreateUpload defines model for CreateUpload.
type CreateUpload struct {
	Path   string `json:"path"`
	Sha256 string `json:"sha256"`
	Size   int    `json:"size"`
}

// Error defines model for Error.
type Error struct {
	Error     string  `json:"error"`
	RequestId *string `json:"requestId,omitempty"`
}

// Publication defines model for Publication.
type Publication struct {
	CommittedAt  *int              `json:"committedAt"`
	CreatedAt    int               `json:"createdAt"`
	ExpiresAt    int               `json:"expiresAt"`
	Id           string            `json:"id"`
	Label        string            `json:"label"`
	RepositoryId string            `json:"repositoryId"`
	Status       PublicationStatus `json:"status"`
}

// PublicationStatus defines model for Publication.Status.
type PublicationStatus string

// Upload defines model for Upload.
type Upload struct {
	Id       string `json:"id"`
	PartSize int    `json:"partSize"`
	Parts    []struct {
		Etag   string `json:"etag"`
		Number int    `json:"number"`
	} `json:"parts"`
	Path   string       `json:"path"`
	Sha256 string       `json:"sha256"`
	Size   int          `json:"size"`
	Status UploadStatus `json:"status"`
}

// UploadStatus defines model for Upload.Status.
type UploadStatus string

// AbortPublication200JSONResponseBodyStatus defines parameters for AbortPublication.
type AbortPublication200JSONResponseBodyStatus string

// GetPublication200JSONResponseBodyStatus defines parameters for GetPublication.
type GetPublication200JSONResponseBodyStatus string

// CommitPublication200JSONResponseBodyStatus defines parameters for CommitPublication.
type CommitPublication200JSONResponseBodyStatus string

// CreatePublicationJSONRequestBody defines body for CreatePublication for application/json ContentType.
type CreatePublicationJSONRequestBody = CreatePublication

// CreateUploadJSONRequestBody defines body for CreateUpload for application/json ContentType.
type CreateUploadJSONRequestBody = CreateUpload

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// CreatePublicationWithBody performs a POST /api/publications (the `CreatePublication` operationId) request,
	// with any type of body and a specified content type.
	CreatePublicationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePublication performs a POST /api/publications (the `CreatePublication` operationId) request.
	// Takes a body of the `application/json` content type.
	CreatePublication(ctx context.Context, body CreatePublicationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AbortPublication performs a DELETE /api/publications/{session} (the `AbortPublication` operationId) request.
	AbortPublication(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPublication performs a GET /api/publications/{session} (the `GetPublication` operationId) request.
	GetPublication(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CommitPublication performs a POST /api/publications/{session}/commit (the `CommitPublication` operationId) request.
	CommitPublication(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUploadWithBody performs a POST /api/publications/{session}/uploads (the `CreateUpload` operationId) request,
	// with any type of body and a specified content type.
	CreateUploadWithBody(ctx context.Context, session string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUpload performs a POST /api/publications/{session}/uploads (the `CreateUpload` operationId) request.
	// Takes a body of the `application/json` content type.
	CreateUpload(ctx context.Context, session string, body CreateUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteUpload performs a POST /api/publications/{session}/uploads/{upload}/complete (the `CompleteUpload` operationId) request.
	CompleteUpload(ctx context.Context, session string, upload string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// CreatePublicationWithBody performs a POST /api/publications (the `CreatePublication` operationId) request,
// with any type of body and a specified content type.
func (c *Client) CreatePublicationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePublicationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePublication performs a POST /api/publications (the `CreatePublication` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) CreatePublication(ctx context.Context, body CreatePublicationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePublicationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AbortPublication performs a DELETE /api/publications/{session} (the `AbortPublication` operationId) request.
func (c *Client) AbortPublication(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAbortPublicationRequest(c.Server, session)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetPublication performs a GET /api/publications/{session} (the `GetPublication` operationId) request.
func (c *Client) GetPublication(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPublicationRequest(c.Server, session)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CommitPublication performs a POST /api/publications/{session}/commit (the `CommitPublication` operationId) request.
func (c *Client) CommitPublication(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCommitPublicationRequest(c.Server, session)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateUploadWithBody performs a POST /api/publications/{session}/uploads (the `CreateUpload` operationId) request,
// with any type of body and a specified content type.
func (c *Client) CreateUploadWithBody(ctx context.Context, session string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUploadRequestWithBody(c.Server, session, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateUpload performs a POST /api/publications/{session}/uploads (the `CreateUpload` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) CreateUpload(ctx context.Context, session string, body CreateUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUploadRequest(c.Server, session, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CompleteUpload performs a POST /api/publications/{session}/uploads/{upload}/complete (the `CompleteUpload` operationId) request.
func (c *Client) CompleteUpload(ctx context.Context, session string, upload string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteUploadRequest(c.Server, session, upload)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreatePublicationRequest calls the generic CreatePublication builder with application/json body
func NewCreatePublicationRequest(server string, body CreatePublicationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePublicationRequestWithBody(server, "application/json", bodyReader)
}

// NewCreatePublicationRequestWithBody constructs an http.Request for the CreatePublication method, with any body, and a specified content type
func NewCreatePublicationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/publications")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAbortPublicationRequest constructs an http.Request for the AbortPublication method
func NewAbortPublicationRequest(server string, session string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "session", session, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/publications/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPublicationRequest constructs an http.Request for the GetPublication method
func NewGetPublicationRequest(server string, session string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "session", session, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/publications/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCommitPublicationRequest constructs an http.Request for the CommitPublication method
func NewCommitPublicationRequest(server string, session string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "session", session, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/publications/%s/commit", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateUploadRequest calls the generic CreateUpload builder with application/json body
func NewCreateUploadRequest(server string, session string, body CreateUploadJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUploadRequestWithBody(server, session, "application/json", bodyReader)
}

// NewCreateUploadRequestWithBody constructs an http.Request for the CreateUpload method, with any body, and a specified content type
func NewCreateUploadRequestWithBody(server string, session string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "session", session, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/publications/%s/uploads", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCompleteUploadRequest constructs an http.Request for the CompleteUpload method
func NewCompleteUploadRequest(server string, session string, upload string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "session", session, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "upload", upload, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/publications/%s/uploads/%s/complete", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// CreatePublicationWithBodyWithResponse performs a POST /api/publications (the `CreatePublication` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	CreatePublicationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePublicationResponse, error)

	// CreatePublicationWithResponse performs a POST /api/publications (the `CreatePublication` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	CreatePublicationWithResponse(ctx context.Context, body CreatePublicationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePublicationResponse, error)

	// AbortPublicationWithResponse performs a DELETE /api/publications/{session} (the `AbortPublication` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	AbortPublicationWithResponse(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*AbortPublicationResponse, error)

	// GetPublicationWithResponse performs a GET /api/publications/{session} (the `GetPublication` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetPublicationWithResponse(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*GetPublicationResponse, error)

	// CommitPublicationWithResponse performs a POST /api/publications/{session}/commit (the `CommitPublication` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	CommitPublicationWithResponse(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*CommitPublicationResponse, error)

	// CreateUploadWithBodyWithResponse performs a POST /api/publications/{session}/uploads (the `CreateUpload` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	CreateUploadWithBodyWithResponse(ctx context.Context, session string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUploadResponse, error)

	// CreateUploadWithResponse performs a POST /api/publications/{session}/uploads (the `CreateUpload` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	CreateUploadWithResponse(ctx context.Context, session string, body CreateUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUploadResponse, error)

	// CompleteUploadWithResponse performs a POST /api/publications/{session}/uploads/{upload}/complete (the `CompleteUpload` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	CompleteUploadWithResponse(ctx context.Context, session string, upload string, reqEditors ...RequestEditorFn) (*CompleteUploadResponse, error)
}

type CreatePublicationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Publication
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreatePublicationResponse) GetJSON201() *Publication {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreatePublicationResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CreatePublicationResponse) GetJSON401() *Error {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CreatePublicationResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CreatePublicationResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreatePublicationResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r CreatePublicationResponse) GetJSON413() *Error {
	return r.JSON413
}

// GetBody returns the raw response body bytes
func (r CreatePublicationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreatePublicationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePublicationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreatePublicationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AbortPublicationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		CommittedAt  *int                                      `json:"committedAt"`
		CreatedAt    int                                       `json:"createdAt"`
		ExpiresAt    int                                       `json:"expiresAt"`
		Id           string                                    `json:"id"`
		Label        string                                    `json:"label"`
		RepositoryId string                                    `json:"repositoryId"`
		Status       AbortPublication200JSONResponseBodyStatus `json:"status"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AbortPublicationResponse) GetJSON200() *struct {
	CommittedAt  *int                                      `json:"committedAt"`
	CreatedAt    int                                       `json:"createdAt"`
	ExpiresAt    int                                       `json:"expiresAt"`
	Id           string                                    `json:"id"`
	Label        string                                    `json:"label"`
	RepositoryId string                                    `json:"repositoryId"`
	Status       AbortPublication200JSONResponseBodyStatus `json:"status"`
} {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r AbortPublicationResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r AbortPublicationResponse) GetJSON401() *Error {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AbortPublicationResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r AbortPublicationResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r AbortPublicationResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r AbortPublicationResponse) GetJSON413() *Error {
	return r.JSON413
}

// GetBody returns the raw response body bytes
func (r AbortPublicationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AbortPublicationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AbortPublicationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AbortPublicationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPublicationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		CommittedAt  *int                                    `json:"committedAt"`
		CreatedAt    int                                     `json:"createdAt"`
		ExpiresAt    int                                     `json:"expiresAt"`
		Id           string                                  `json:"id"`
		Label        string                                  `json:"label"`
		RepositoryId string                                  `json:"repositoryId"`
		Status       GetPublication200JSONResponseBodyStatus `json:"status"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetPublicationResponse) GetJSON200() *struct {
	CommittedAt  *int                                    `json:"committedAt"`
	CreatedAt    int                                     `json:"createdAt"`
	ExpiresAt    int                                     `json:"expiresAt"`
	Id           string                                  `json:"id"`
	Label        string                                  `json:"label"`
	RepositoryId string                                  `json:"repositoryId"`
	Status       GetPublication200JSONResponseBodyStatus `json:"status"`
} {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetPublicationResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetPublicationResponse) GetJSON401() *Error {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetPublicationResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetPublicationResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r GetPublicationResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r GetPublicationResponse) GetJSON413() *Error {
	return r.JSON413
}

// GetBody returns the raw response body bytes
func (r GetPublicationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetPublicationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPublicationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPublicationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CommitPublicationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		CommittedAt  *int                                       `json:"committedAt"`
		CreatedAt    int                                        `json:"createdAt"`
		ExpiresAt    int                                        `json:"expiresAt"`
		Id           string                                     `json:"id"`
		Label        string                                     `json:"label"`
		RepositoryId string                                     `json:"repositoryId"`
		Status       CommitPublication200JSONResponseBodyStatus `json:"status"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CommitPublicationResponse) GetJSON200() *struct {
	CommittedAt  *int                                       `json:"committedAt"`
	CreatedAt    int                                        `json:"createdAt"`
	ExpiresAt    int                                        `json:"expiresAt"`
	Id           string                                     `json:"id"`
	Label        string                                     `json:"label"`
	RepositoryId string                                     `json:"repositoryId"`
	Status       CommitPublication200JSONResponseBodyStatus `json:"status"`
} {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CommitPublicationResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CommitPublicationResponse) GetJSON401() *Error {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CommitPublicationResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CommitPublicationResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CommitPublicationResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r CommitPublicationResponse) GetJSON413() *Error {
	return r.JSON413
}

// GetBody returns the raw response body bytes
func (r CommitPublicationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CommitPublicationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CommitPublicationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CommitPublicationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateUploadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Upload
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CreateUploadResponse) GetJSON200() *Upload {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateUploadResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CreateUploadResponse) GetJSON401() *Error {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CreateUploadResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CreateUploadResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateUploadResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r CreateUploadResponse) GetJSON413() *Error {
	return r.JSON413
}

// GetBody returns the raw response body bytes
func (r CreateUploadResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateUploadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUploadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateUploadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CompleteUploadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Upload
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CompleteUploadResponse) GetJSON200() *Upload {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CompleteUploadResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CompleteUploadResponse) GetJSON401() *Error {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CompleteUploadResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CompleteUploadResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CompleteUploadResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r CompleteUploadResponse) GetJSON413() *Error {
	return r.JSON413
}

// GetBody returns the raw response body bytes
func (r CompleteUploadResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CompleteUploadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteUploadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CompleteUploadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreatePublicationWithBodyWithResponse performs a POST /api/publications (the `CreatePublication` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CreatePublicationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePublicationResponse, error) {
	rsp, err := c.CreatePublicationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePublicationResponse(rsp)
}

// CreatePublicationWithResponse performs a POST /api/publications (the `CreatePublication` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CreatePublicationWithResponse(ctx context.Context, body CreatePublicationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePublicationResponse, error) {
	rsp, err := c.CreatePublication(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePublicationResponse(rsp)
}

// AbortPublicationWithResponse performs a DELETE /api/publications/{session} (the `AbortPublication` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) AbortPublicationWithResponse(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*AbortPublicationResponse, error) {
	rsp, err := c.AbortPublication(ctx, session, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAbortPublicationResponse(rsp)
}

// GetPublicationWithResponse performs a GET /api/publications/{session} (the `GetPublication` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetPublicationWithResponse(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*GetPublicationResponse, error) {
	rsp, err := c.GetPublication(ctx, session, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPublicationResponse(rsp)
}

// CommitPublicationWithResponse performs a POST /api/publications/{session}/commit (the `CommitPublication` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CommitPublicationWithResponse(ctx context.Context, session string, reqEditors ...RequestEditorFn) (*CommitPublicationResponse, error) {
	rsp, err := c.CommitPublication(ctx, session, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCommitPublicationResponse(rsp)
}

// CreateUploadWithBodyWithResponse performs a POST /api/publications/{session}/uploads (the `CreateUpload` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CreateUploadWithBodyWithResponse(ctx context.Context, session string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUploadResponse, error) {
	rsp, err := c.CreateUploadWithBody(ctx, session, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUploadResponse(rsp)
}

// CreateUploadWithResponse performs a POST /api/publications/{session}/uploads (the `CreateUpload` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CreateUploadWithResponse(ctx context.Context, session string, body CreateUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUploadResponse, error) {
	rsp, err := c.CreateUpload(ctx, session, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUploadResponse(rsp)
}

// CompleteUploadWithResponse performs a POST /api/publications/{session}/uploads/{upload}/complete (the `CompleteUpload` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CompleteUploadWithResponse(ctx context.Context, session string, upload string, reqEditors ...RequestEditorFn) (*CompleteUploadResponse, error) {
	rsp, err := c.CompleteUpload(ctx, session, upload, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteUploadResponse(rsp)
}

// ParseCreatePublicationResponse parses an HTTP response from a CreatePublicationWithResponse call
func ParseCreatePublicationResponse(rsp *http.Response) (*CreatePublicationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePublicationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Publication
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	}

	return response, nil
}

// ParseAbortPublicationResponse parses an HTTP response from a AbortPublicationWithResponse call
func ParseAbortPublicationResponse(rsp *http.Response) (*AbortPublicationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AbortPublicationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			CommittedAt  *int                                      `json:"committedAt"`
			CreatedAt    int                                       `json:"createdAt"`
			ExpiresAt    int                                       `json:"expiresAt"`
			Id           string                                    `json:"id"`
			Label        string                                    `json:"label"`
			RepositoryId string                                    `json:"repositoryId"`
			Status       AbortPublication200JSONResponseBodyStatus `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	}

	return response, nil
}

// ParseGetPublicationResponse parses an HTTP response from a GetPublicationWithResponse call
func ParseGetPublicationResponse(rsp *http.Response) (*GetPublicationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPublicationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			CommittedAt  *int                                    `json:"committedAt"`
			CreatedAt    int                                     `json:"createdAt"`
			ExpiresAt    int                                     `json:"expiresAt"`
			Id           string                                  `json:"id"`
			Label        string                                  `json:"label"`
			RepositoryId string                                  `json:"repositoryId"`
			Status       GetPublication200JSONResponseBodyStatus `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	}

	return response, nil
}

// ParseCommitPublicationResponse parses an HTTP response from a CommitPublicationWithResponse call
func ParseCommitPublicationResponse(rsp *http.Response) (*CommitPublicationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CommitPublicationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			CommittedAt  *int                                       `json:"committedAt"`
			CreatedAt    int                                        `json:"createdAt"`
			ExpiresAt    int                                        `json:"expiresAt"`
			Id           string                                     `json:"id"`
			Label        string                                     `json:"label"`
			RepositoryId string                                     `json:"repositoryId"`
			Status       CommitPublication200JSONResponseBodyStatus `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	}

	return response, nil
}

// ParseCreateUploadResponse parses an HTTP response from a CreateUploadWithResponse call
func ParseCreateUploadResponse(rsp *http.Response) (*CreateUploadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUploadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Upload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	}

	return response, nil
}

// ParseCompleteUploadResponse parses an HTTP response from a CompleteUploadWithResponse call
func ParseCompleteUploadResponse(rsp *http.Response) (*CompleteUploadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompleteUploadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Upload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	}

	return response, nil
}
